services:

  db:
    image: mariadb:11.0.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  web:
    image: nginx:1.25.2
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  data:
    driver: "local"